# Generated by Django 3.2.15 on 2022-09-12 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_day', models.CharField(choices=[('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Tue', max_length=10)),
                ('booking_time', models.CharField(choices=[('17.00-18.30', '17.00-18.30'), ('18.30-20.00', '18.30-20.00'), ('20.00-21.30', '20.00-21.30')], default='17.00-18.30', max_length=20)),
                ('number_of_guests', models.CharField(choices=[('One guest', 'One guest'), ('Two guests', 'Two guests'), ('Three guests', 'Three guests'), ('Four guests', 'Four guests'), ('Five guests', 'Five guests'), ('Six guests', 'Six guests'), ('Seven guests', 'Seven guests'), ('Eight guests', 'Eight guests')], default='Two guests', max_length=20)),
                ('allergies', models.TextField(blank=True, max_length=100, verbose_name='Allergies')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(blank=True, max_length=25, verbose_name='Phone')),
                ('guest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('booking_day', 'booking_time'),
                'unique_together': {('guest_name', 'booking_day', 'booking_time')},
            },
        ),
    ]
