# Generated by Django 3.2.15 on 2022-09-13 12:17

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=100, unique=True)),
                ('course_type', models.CharField(choices=[('Starters', 'Starters'), ('Main courses', 'Main courses'), ('Deserts', 'Deserts')], default='Main courses', max_length=12)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('booking_week', 'booking_day', 'booking_time')},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guest_name',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_week',
            field=models.CharField(choices=[('Current week', 'This week'), ('Next week', 'Next week')], default='Current week', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('guest', 'booking_week', 'booking_day', 'booking_time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_phone',
        ),
    ]
