# Generated by Django 3.2.15 on 2022-09-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0003_auto_20220915_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('course_type', 'course_image', 'course_name', 'course_description')},
        ),
    ]
